name: Infrastructure Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - test
        - prod
      action:
        description: 'Deployment action'
        required: true
        default: 'deploy'
        type: choice
        options:
        - deploy
        - what-if
        - destroy

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Set Resource Group Name
      run: |
        echo "RESOURCE_GROUP_NAME=MemberPropertyMarketAlert-${{ github.event.inputs.environment }}-rg" >> $GITHUB_ENV

    - name: Create Resource Group
      if: github.event.inputs.action == 'deploy'
      run: |
        az group create \
          --name ${{ env.RESOURCE_GROUP_NAME }} \
          --location "East US" \
          --tags \
            Environment=${{ github.event.inputs.environment }} \
            Project=MemberPropertyMarketAlert \
            ManagedBy=GitHub-Actions
            
    - name: Validate Bicep Template
      if: github.event.inputs.action != 'destroy'
      run: |
        az deployment group validate \
          --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
          --template-file ./infra/main.bicep \
          --parameters ./infra/main.${{ github.event.inputs.environment }}.parameters.json
          
    - name: What-If Deployment
      if: github.event.inputs.action == 'what-if'
      run: |
        az deployment group what-if \
          --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
          --template-file ./infra/main.bicep \
          --parameters ./infra/main.${{ github.event.inputs.environment }}.parameters.json \
          --name memberpropertyalert-whatif-${{ github.run_number }}
          
    - name: Deploy Infrastructure
      if: github.event.inputs.action == 'deploy'
      id: deploy
      run: |
        az deployment group create \
          --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
          --template-file ./infra/main.bicep \
          --parameters ./infra/main.${{ github.event.inputs.environment }}.parameters.json \
          --name memberpropertyalert-${{ github.run_number }}
          
    - name: Get Deployment Outputs
      if: github.event.inputs.action == 'deploy'
      run: |
        echo "## Deployment Outputs" >> $GITHUB_STEP_SUMMARY
        
        FUNCTION_APP_NAME=$(az deployment group show \
          --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
          --name memberpropertyalert-${{ github.run_number }} \
          --query "properties.outputs.functionAppName.value" \
          --output tsv)
        
        WEB_APP_NAME=$(az deployment group show \
          --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
          --name memberpropertyalert-${{ github.run_number }} \
          --query "properties.outputs.webAppName.value" \
          --output tsv)
        
        FUNCTION_APP_URL=$(az deployment group show \
          --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
          --name memberpropertyalert-${{ github.run_number }} \
          --query "properties.outputs.functionAppUrl.value" \
          --output tsv)
        
        WEB_APP_URL=$(az deployment group show \
          --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
          --name memberpropertyalert-${{ github.run_number }} \
          --query "properties.outputs.webAppUrl.value" \
          --output tsv)
        
        echo "- **Function App**: [$FUNCTION_APP_NAME]($FUNCTION_APP_URL)" >> $GITHUB_STEP_SUMMARY
        echo "- **Web App**: [$WEB_APP_NAME]($WEB_APP_URL)" >> $GITHUB_STEP_SUMMARY
        echo "- **Environment**: ${{ github.event.inputs.environment }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Resource Group**: ${{ env.RESOURCE_GROUP_NAME }}" >> $GITHUB_STEP_SUMMARY
        
    - name: Destroy Infrastructure
      if: github.event.inputs.action == 'destroy'
      run: |
        echo "⚠️ Destroying infrastructure for environment: ${{ github.event.inputs.environment }}"
        az group delete \
          --name ${{ env.RESOURCE_GROUP_NAME }} \
          --yes \
          --no-wait
        echo "Resource group deletion initiated. This may take several minutes to complete."
